Implement Breadcrumbs component
reactioncommerce/kinetic pull request #116
Opened 2022-11-08 10:17 UTC by vannguyenn

Resolves #92
Figma: https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=1717%3A13491

Testing Instructions:
- Start the app and login with a valid account
- Breadcrumbs component should display on  all pages
- If breadcrumbs have more than 2 items, it will display '...' in the middle
- Click '...' to display all breadcrumbs items
 
Screenshots
<img width="2028" alt="Screen Shot 2022-10-31 at 10 14 46" src="https://user-images.githubusercontent.com/33818318/198923632-4421826f-9350-4af4-9fa9-fa132cd81b2e.png">
<img width="2028" alt="Screen Shot 2022-10-31 at 10 14 23" src="https://user-images.githubusercontent.com/33818318/198923638-11df6feb-7208-44b7-96aa-b424dbd189f5.png">

2022-11-09 10:00 UTC, zenweasel approved these changes

2022-11-29 17:27 UTC, tedraykov requested changes
In my opinion, the most appropriate place to get the breadcrumb title is from the route object itself. I don't feel great about having a separate place for the breadcrumb titles.

We can augment the RouteObject to have `title` property and use it for the breadcrumbs. I had this proposal before and this is yet another example of why the routes should have human-readable titles attached to them.

### RouteObject type augmentation

This could be added in the the `routes.tsx` directly or in a separate file in the types directory and then imported in the `routes.tsx`
```typescript
declare module "react-router-dom" {
  export interface RouteObject {
    title?: string
  }
}
```

This allows us to add a title to each route:

```typescript
...
{
  path: "settings",
  title: "Settings",
  children: [
  ...
}
...
```

### Map of all URLs to Titles

In order to create a map between all URLs in the app and their corresponding title from the route definitions we can traverse and create a flat map as such:

```typescript
"/": "/"
"/*": "Not Found"
"/settings": "Settings"
"/settings/checkout":  "Checkout"
"/settings/checkout/address-validation": "Address Validation"
"/settings/checkout/taxes": "Taxes"
...
```

An example traversal algorithm:

```typescript
/*
 * key: the full path for the route
 * value: the title of the route
 */
type RouteTitleMap = Record<string, string>

const routesToTitleMap: RouteTitleMap = {};
const stack: [RouteObject, string[]][] = [];

for (const route of routes) {
  stack.push([route, [route.path || ""]]);
  while (stack.length) {
    const stackElement = stack.pop();
    if (!stackElement) continue;

    const [currentRoute, pathnames] = stackElement;
    if (currentRoute.children) {
      currentRoute.children.forEach((childRoute) => {
        stack.push([childRoute, [...pathnames, childRoute.path || ""]]);
      });
    }

    if (!currentRoute?.path) {
      continue;
    }
    const routePathname = pathnames.filter((pathname) => pathname !== "")
      .join("/")
      .replace("//", "/");

    routesToTitleMap[routePathname] = currentRoute?.title || currentRoute.path;
  }
}
return routesToTitleMap;
```

> This is a DFS algorithm. The implementation is a bit long but it doesn't use recursion because recursion is slower and more dangerous.

To get access to the flat map we can create a `RoutesProvider` that can be accessed from the `Breadcrumbs` component directly.

```typescript
// App.tsx
...
function App() {
  const routeElement = useRoutes(routes);

  return (
         ...
            <RoutesProvider routes={routes}>
              {routeElement}
            </RoutesProvider>
         ...
  );
}
```

And inside the `RoutesProvider`, we can calculate the flat map:

```typescript
// RoutesProvider/index.tsx
...
export const RoutesProvider = ({ children, routes }: RoutesProviderProps) => {
  const routeMap = useMemo(() => {
    ...
    // Traversal algorithm here
    ...
    return routesToTitleMap;
  }, [routes]);

  return <RoutesContext.Provider value={{ routes, routeMap }}>{children}</RoutesContext.Provider>;
};
```

We can use the context hook to access the routes-to-title map in the breadcrumbs component:
```typescript
export const Breadcrumbs = ({ sx }: BreadcrumbsProps) => {
  ...
  const { routeMap } = useRoutes();
  ...
  return (
    ...
    <BreadcrumbItem to={to} key={to} label={`${routeMap[to]}`} last={last} />
    ...
  );
};
```

### Other uses:
Having this route-to-title map globally accessible will allow us to also add a title to the browser tab. 
Also, we may introduce a global search in the future that can search for views by their title.
And all of this, while having a single place to define those titles - in the route definitions in the `routes.tsx` file

Let me know if you have objections to this.

2022-11-29 17:27 UTC, tedraykov commented on src/routes.tsx
> +                element: <Navigate to="users-and-permissions" replace />
Instead of flattening all children, you can add an index child element that navigates to `users-and-permissions`.
```typescript
path: "settings",
children: [
  {
    index: true,
    element: <Navigate to="users-and-permissions" replace />
  },
  ...
}
```

2022-11-29 17:27 UTC, tedraykov commented on package.json
> +    "react-router-dom": "6.4.1",
Let's support latest minor version.
```suggestion
    "react-router-dom": "^6.4.1",
```

2022-11-29 17:27 UTC, tedraykov commented on src/components/Breadcrumb/LinkRouter.tsx
> +interface LinkRouterProps extends LinkProps {
Using type picking seems better here because the `to` property in the react-router `Link` component is not a string
```suggestion
type LinkRouterProps = LinkProps & Pick<ReactRouterLinkProps, "to" | "replace">
```

2022-11-29 17:27 UTC, tedraykov commented on src/components/Breadcrumb/LinkRouter.tsx
> +export const LinkRouter = (props: LinkRouterProps) => (
I feel like RouterLink is a better name for this component.
To avoid react-router name conflict you can rename the import to 
```typescript
import { Link as ReactRouterLink, LinkProps as ReactRouterLinkProps } from "react-router-dom";
```

2022-12-05 09:29 UTC, vannguyenn commented
Hi @tedraykov, thank you for your feedback. I thought about the idea that we could provide a title property inside the route object and centralize all the page data (including breadcrumb) there. However, we could not avoid the use case where a page needs to update the breadcrumb inside the component, for example, on the promotion details page, where the last item of the breadcrumb needs to be the promotion's name which is not visible at the route level at the moment. And also, we need to update that breadcrumb when users successfully updated the promotion's name. This is just 1 example, but I think we still need to allow the child components to update the breadcrumb accordingly.

2022-12-12 13:18 UTC, tedraykov approved these changes
Supporting dynamic route titles doesn't contradict the ability to support static route titles. The breadcrumbs context can get the route names from the route definitions, instead of a separate file and have a different API for setting the breadcrumb title of a dynamic route such as the promotion details view. I think ideally even dynamic titles should be defined in the routes file as well, but instead of providing a string, we can provide a resolver function.
Static and dynamic route title is quite a common use case in larger apps and Angular for example supports this out of the box. https://angular.io/api/router/Route#description

Let's merge this and call it a day because my request is a bit out of scope for this PR and we have a lot of work to merge already.

2022-12-13 02:59 UTC, vannguyenn commented
Thanks @tedraykov, I just found out that react-router has support for this kind of breadcrumbs https://reactrouter.com/en/main/hooks/use-matches#breadcrumbs. I will merge this PR first, and try to find a way to improve this.

2022-12-13 03:00 UTC, merged