Prepare error handler component
reactioncommerce/kinetic pull request #117
Opened 2022-11-08 10:44 UTC by vannguyenn

Signed-off-by: Chloe <pinkcloudvnn@gmail.com>

2022-11-09 09:50 UTC, zenweasel commented
I feel like the message "Network Error" just because it can't reach the API server might cause a little confusion. Could be nothing to do with Network and just the server is down. Should be make it more clear that the issue is reaching the API server?

2022-12-05 06:15 UTC, zenweasel requested changes
I think the wording on this error needs work to be more clear as I think the current wording could be confusing.

If the error is thrown when we can't reach the API server, it should probably explicitly say that rather than implying it's a general internet error (which it may be or it might not be)


Otherwise the message is shown as expected.

2022-12-05 09:33 UTC, vannguyenn commented
Thanks, @zenweasel, I will update the error message.

2022-12-12 18:19 UTC, tedraykov commented on src/containers/AccountProvider/index.tsx
> +      if (!formatErrorResponse(error)) {
Why do we conditionally set the error boundary here?
Also, in what case is the `error.response` is falsely?

2022-12-12 18:19 UTC, tedraykov commented on src/components/ErrorBoundary/GeneralError.tsx
> +export const GeneralError = ({ title = "Something went wrong.", description = "Email you shop owner to get access." }:GeneralErrorProps) => (
`Contact you shop owner to get access.` is more generic and fit's better here IMO because email is not the only way to contact an admin.

2022-12-13 07:18 UTC, vannguyenn commented on src/containers/AccountProvider/index.tsx
> +      if (!formatErrorResponse(error)) {
When the errors come from API servers (invalid tokens, permissions, etc...) we will not use the global error boundary.

2022-12-13 08:57 UTC, tedraykov approved these changes

2022-12-14 00:36 UTC, zenweasel approved these changes

2022-12-15 01:42 UTC, merged