Promotions usage limits
reactioncommerce/kinetic pull request #157
Opened 2022-12-28 04:38 UTC by vannguyenn

Resolves #132, #149

2023-01-12 16:54 UTC, zenweasel approved these changes

2023-01-18 09:15 UTC, tedraykov requested changes
The code looks good. I'm not a great fan of the labels text:
<img width="974" alt="Screenshot 2023-01-18 at 11 03 45" src="https://user-images.githubusercontent.com/32718995/213128822-50c4ba6f-8957-4589-8aac-8a2290d56c26.png">

Potentially we can have a move concise label and a helper icon with a tooltip to the right of it that provides more detailed context about the field.

In the case of using the label `Max` as shorthand for `maximum` and using `#` as shorthand for `number of` and it seems a bit informal. 
I would suggest labels like "Total uses", "Uses per Customer" and "Discount Amount Limit" plus tooltips that give extra details.

I see that these labels are used in the design as well so if we already have consensus on them, we can merge them as is.

2023-01-26 06:43 UTC, vannguyenn commented
Thanks @tedraykov, I left comments for @brendan-shea-pm

2023-01-30 03:42 UTC, vannguyenn commented
Hi @tedraykov, here is the reply from @brendan-shea-pm https://github.com/reactioncommerce/kinetic/issues/150#issuecomment-1407831652. He suggested that we should keep the label as is.

2023-02-06 18:53 UTC, tedraykov approved these changes

2023-02-07 01:08 UTC, merged