Should send single value when creating inclusion/exclusion rules with `equal` operator
reactioncommerce/kinetic pull request #193
Opened 2023-02-13 11:25 UTC by vannguyenn

Resolves #192 

Testing Instructions:
- Start the app and login with a valid account
- Navigate to Promotions
- Click Actions -> Create New
- Create a promotion with an inclusion/exclusion rule
- Select `Is` Operator
<img width="2116" alt="image" src="https://user-images.githubusercontent.com/33818318/218444663-173e0506-c991-456d-8aa1-a75cf814a970.png">
Expected Inclusions rule

```

 inclusionRules:  {
    "conditions": {
        "all": [
            {
                "fact": "item",
                "path": "$.productVendor",
                "value": "EMS",
                "operator": "equal"
            }
        ]
    }
}

```
- Select `Is Any Of` Operator

```
inclusionRules: {
    "conditions": {
        "all": [
            {
                "fact": "item",
                "path": "$.productVendor",
                "value": [
                    "EMS"
                ],
                "operator": "in"
            }
        ]
    }
}
```

2023-02-14 05:07 UTC, zenweasel requested changes
Not correctly handling when switching from "is" to "is any of" with a single value

2023-02-14 05:43 UTC, zenweasel approved these changes
My mistake, PR is working correctly.

2023-02-27 13:16 UTC, tedraykov requested changes
Functionally looks good.

Only comment is the autocomplete tag increases the height of the field by 2 pixels:
<img width="625" alt="Screenshot 2023-02-27 at 15 13 40" src="https://user-images.githubusercontent.com/32718995/221573256-69427f87-2796-4907-8878-9d70afb725c8.png">
This can be fixed by changing the margin in the `theme.ts` like so:
```js
MuiAutocomplete: {
      styleOverrides: {
        tag: {
          color: color.grey[600],
          fontWeight: 400,
          borderRadius: baseTheme.shape.borderRadius,
          margin: 2,    // <==========
          svg: {
            fontSize: 12,
            fill: color.grey[600]
          }
        }
      }
    },
```

2023-03-08 12:59 UTC, tedraykov approved these changes

2023-03-10 00:38 UTC, merged