Customer Listing Page Layout
reactioncommerce/kinetic pull request #99
Opened 2022-11-01 09:15 UTC by vannguyenn

Resolves #85
Figma: https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=1717%3A12788

Testing Instructions:
- Start the app and login with a valid account
- Navigate to Customers
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/33818318/199198612-9b441389-e588-4f1e-a155-9834d92dda62.png">

Note: 
- Filters section is hidden while waiting for support from API side
- Checkbox columns will be implemented in the export tickets since it doesn't make sense to the selection column without any actions

2022-11-03 08:43 UTC, zenweasel requested changes
In list page I was able to select "Page -1 of 0" and then it started giving me a bunch of errors on the server side saying `Skip value must be non-negative, but received: -10`.

Just an issue with that pagination selector I imagine. Still need to test with actual customers since I did this with 0 customers

2022-12-05 06:01 UTC, zenweasel requested changes
Two more more issues with the pagination:

1. If I switch to 5 records per page, go to the second page and then switch back to 10 I get "Page 2 of 1"
2. When using 10 records per page, if I go to the second page and back again it still says "Page 2 of 2"
![image](https://user-images.githubusercontent.com/72819/205560649-7c016fd9-d125-4b5f-908d-81193ae42d00.png)

2022-12-05 09:14 UTC, vannguyenn commented
Thanks @zenweasel , I have fixed the pagination issue. Now it should work as expected

2022-12-05 09:20 UTC, zenweasel approved these changes

2022-12-12 13:35 UTC, tedraykov commented on src/containers/Layouts/PageLayout.tsx
> +    {headers ? <SubHeader items={headers} /> : <Paper variant="outlined" square sx={{ minHeight: 43 }}/>}
Why do we need an empty paper here? I see that it's also used in the Figma designs but it serves no purpose.

2022-12-12 13:37 UTC, tedraykov approved these changes
Looks great. I'm only not a fan of the empty page header.

2022-12-13 06:43 UTC, vannguyenn commented on src/containers/Layouts/PageLayout.tsx
> +    {headers ? <SubHeader items={headers} /> : <Paper variant="outlined" square sx={{ minHeight: 43 }}/>}
We can remove this header I think. Maybe we plan to have another page inside the Customers master page.

2022-12-13 06:53 UTC, merged